---
title: "Locations (Norway)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Locations (Norway)}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(csdata)
library(data.table)
library(magrittr)
```

`csdata::nor_locations_names()` lists the valid locations and location types.

The table below lists every `location_code` alongside its `location_name_description_nb`. These are the two location fields used most often in practice. `location_code` appears in datasets and file names. `location_name_description_nb` appears in figures, tables and documents.

```{r echo=FALSE, results='asis'}
d <- csdata::nor_locations_names()[, .(
  location_order = paste0("#", location_order),
  location_code,
  location_name_description_nb
)]

gt::gt(d) %>%
  gt::tab_options(
    table.width = "750px"
  ) %>%
  gt::tab_header(title = "Reference table of location_code and location_name_description_nb") %>%
  gt::cols_label(
    location_order = "#"
  )
```
